# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f337126b843b3ecae46da5e6b7354ed9a58345e06c378cdbc827f0927d143680a446429d7ba3cf45a97992c81fc0efc3a9c4af67fde8d9fe2ddcba2a83ef218

test:
  secret_key_base: 116a812feaa8a98d36cb99e27e6136f2176142c0cc5b8d11b10295bc3eb9c261ac039bfc27d7ef48f968b90167d7ca5fd4f35e81c456910e4365db8a7f6e62c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
